<a href="https://colab.research.google.com/github/Klyeil/gamza/blob/main/relationship.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

#1
A = {1,2,3}
B = {2,3,4}
R = {(1,2), (2,3), (3,2), (3,4)}

print("관계 R:", R)

#2
A_list = sorted(A)
B_list = sorted(B)

relation_matrix = np.zeros((len(A_list), len(B_list)), dtype = int)

for i, a in enumerate(A_list):
  for j, b in enumerate(B_list):
    relation_matrix[i, j] = 1

print("관계 행렬 (raws: A, columns: B):")
print(relation_matrix)

#3
C = {'x', 'y'}
S = {(2, 'x'), (3,'y'), (4,'x')}

composed_relation = set()

for (a, b1) in R:
  for (b2, c) in S:
    if b1 == b2:
      composed_relation.add((a,c))

print("\n합성관계 R = S :", composed_relation)



관계 R: {(2, 3), (3, 2), (1, 2), (3, 4)}
관계 행렬 (raws: A, columns: B):
[[1 1 1]
 [1 1 1]
 [1 1 1]]


NameError: name 'x' is not defined